name: mob4pay_tech_challenge
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  path: ^1.9.1
  result_dart: ^2.0.0
  retrofit: ^4.4.2
  sqflite: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
  mockito: ^5.4.5
  retrofit_generator: '>=9.0.0 <10.0.0'
  sqflite_common_ffi: ^2.3.5

flutter:
  uses-material-design: true
