name: mob4pay_tech_challenge
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  auto_route: ^10.0.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  path: ^1.9.1
  provider: ^6.1.2
  result_dart: ^2.0.0
  retrofit: ^4.4.2
  sqflite: ^2.4.2

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
  mockito: ^5.4.5
  retrofit_generator: '>=9.0.0 <10.0.0'
  sqflite_common_ffi: ^2.3.5

flutter:
  uses-material-design: true
  assets:
    - assets/
