// Mocks generated by Mockito 5.4.5 from annotations
// in mob4pay_tech_challenge/test/src/data/customers/repositories/customers_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mob4pay_tech_challenge/src/data/customers/data_sources/customers_local_data_source.dart'
    as _i5;
import 'package:mob4pay_tech_challenge/src/data/customers/data_sources/customers_remote_data_source.dart'
    as _i2;
import 'package:mob4pay_tech_challenge/src/domain/customers/models/customer.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CustomersRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomersRemoteDataSource extends _i1.Mock
    implements _i2.CustomersRemoteDataSource {
  @override
  _i3.Future<List<_i4.Customer>> fetchCustomers() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCustomers, []),
            returnValue: _i3.Future<List<_i4.Customer>>.value(<_i4.Customer>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Customer>>.value(
              <_i4.Customer>[],
            ),
          )
          as _i3.Future<List<_i4.Customer>>);
}

/// A class which mocks [CustomersLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomersLocalDataSource extends _i1.Mock
    implements _i5.CustomersLocalDataSource {
  @override
  _i3.Future<void> deleteCustomers() =>
      (super.noSuchMethod(
            Invocation.method(#deleteCustomers, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Customer>> getCustomers() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomers, []),
            returnValue: _i3.Future<List<_i4.Customer>>.value(<_i4.Customer>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Customer>>.value(
              <_i4.Customer>[],
            ),
          )
          as _i3.Future<List<_i4.Customer>>);

  @override
  _i3.Future<void> saveCustomer(_i4.Customer? customer) =>
      (super.noSuchMethod(
            Invocation.method(#saveCustomer, [customer]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
